### ISSUE TITLE
set defaultLayout and partials render  questions in koa2  koa-views hbs  

### ISSUE THREAD

**Issue by windbell2** [queckezz/koa-views#77]
1,How to set defautlayout with handlebars
2,my code:

``` javascript
app.use(views(__dirname+"/views", {
    extension: 'hbs',
    map: { hbs: 'handlebars' },
    options: {
        partials: {
            error: './error' 
        }
    }
}));
```

routes/index.js

``` javascript
var router = require('koa-router')();
router.get('/', async function (ctx, next) {
  ctx.state = {
    title: 'koa2 title'
  };

  await ctx.render('index', {
  });
})
module.exports = router;
```

views/index.hbs

``` html
{{> error }}

<h1>{{title}}</h1>
<p>Welcome to {{title}}</p>
```

first time render ok,
but, when i refresh the browser.display an error:

``` code
  xxx GET / 500 12ms -
{ Error: ENOENT: no such file or directory, open 'C:\study\koa2\koa2-hbs\views\error

<h1>{{message}}<\h1>
<h2>{{error.status}}<\h2>
<pre>{{error.stack}}<\pre>
.hbs'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\study\\koa2\\koa2-hbs\\views\\error\n\n<h1>{{message}}<\\h1>\n<h2>{{error.status}}<\\h2>\n<pre>{{error.stack}}<\\pre>\n.hbs' }
```

**Comment by sanpojoe** [comment]
Did you find a solution to this? I'm getting the same thing, initial load is fine but when I then refresh I get this error:

```
Error: ENOENT: no such file or directory, open '/home/joe/Documents/LSDM/views/<head>
    <title>{{pageTitle}}</title>
    <meta name="description" content="Awesome Description Here">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="/base.css" />
  </head>
  .hbs'

```

**Comment by sanpojoe** [comment]
Moving the partials into the render method seems to have fixed the problem:

```
import Koa from 'koa';
import Router from 'koa-router';
import serve from 'koa-static';
import views from 'koa-views';
import path from 'path';

const app = new Koa();

app.use(serve('./res'));
app.use(views(path.resolve(__dirname, '../views'), {
  map: {
    hbs: 'handlebars',
  },
  extension: 'hbs',
}));

const router = new Router()
  .get('/', async (ctx) => {
    await ctx.render('index', { title: 'koa-hbs',
      partials: {
        Head: './partials/head',
        Header: './partials/header',
      },
    });
  });

app.use(router.routes());
app.listen(3000);

```

**Comment by wsmPanda** [comment]
and in new version 'partials' did not work at all...

**Comment by sanpojoe** [comment]
still an issue in 5.2.0

**Comment by sanpojoe** [comment]
so it seems like this is by design in consolidate:

https://github.com/tj/consolidate.js/issues/100#issuecomment-16009960

**Comment by q545244819** [comment]
@sanpoChew This method dosen't solve that problem, my `koa-view` version is `5.2.0`. It still have this problem. Even you post another solution it dosen't work.

**Comment by ianstormtaylor** [comment]
Getting this same problem still...

**Comment by q545244819** [comment]
@ianstormtaylor I already give up this module. if you use handlebars as a temple, I suggest you chosing koa-hbs. It also support koa2.

**Comment by queckezz** [comment]
PR would be welcome. I don't use koa personally anymore, so this is not something that's on my todo list. If anyone wants to step up as a maintainer, feel free!

**Comment by wsmPanda** [comment]
@queckezz i thank i just findout somewhere faulted, let me join it

**Comment by DJviolin** [comment]
OFF

If you really want to use Handlebars like templating in Koa v2 and most of the modules not supporting partials yet (like this one), try Nunjucks (made by Mozilla). It does what Handlebars do, but it's much better (and I believe slightly faster). The partials logic handled in the templates, meaning you don't need specific package that's supporting it. I wrote my lightweight Nunjucks parser which not requires `koa-views` package: https://gist.github.com/DJviolin/4111b463daf973b6867164a2337c1a75

Or if you are crazy enough, you can try to use template literals, which is part of the standard library and you outputting the rendering by calling `ctx.body` or `res.send` in Express (like what a templating library does): :)
https://github.com/DJviolin/template-literals-demo
Be advised that because all of your templating logic is written by you in this case (like a css), there aren't any standard yet what are the best practices for this.

ON

**Comment by sanpoChew** [comment]
Yeah i started using koa-hbs as well

I've got to say though, using template literals is something I've never even considered before. Might have a play with it. I was planning to try something other than Handlebars for future projects anyway.

**Comment by DJviolin** [comment]
@sanpoChew I'm just experimenting with it as well. Worth it to note that some things much easier then a templating engine, some more complex (like for loops, if you have custom structure, placing multiple objects in it, every time you have to write a custom function for it). But for the plus side, you will have a proper error handling (try/catch block in my loop.js).

One of the easiest parts that you still just writing plain Javascript. For example, I also included simple translation logic in my demo. The site language should have a default value (en-US), when not referenced in a router (otherwise it will give you error). I just used a simple OR operator and it works:

```js
<html class="no-js" lang="${obj.lang || 'en-US'}">
```

One of the hardest thing is passing down a value from the router to 2 or 3 levels deep without referencing a template file more than once (like you have the main template part which is getting the data from the router, which is in the main layout, which is calling the header, and the header also should have data from the router). My solution was to use objects in the function arguments. This way I can daisy chain objects from the router all the way down to a partial. I'm not sure though in a much more complex project, with hundreds of partials, components, how easy would be this to manage.

**Comment by queckezz** [comment]
Yes, you can see this movement also in a lot of frontend frameworks like for example [choo](https://github.com/yoshuawuyts/choo) or [hyperapp](https://www.npmjs.com/package/hyperapp)

@DJviolin, can your `loop` component not also just be expressed simply by using an `array.map`?
```js
module.exports = `
  <ul>
    ${array.map((item) => `<li>${item}</li>`)}
  </ul>
`
```

So `koa-views` is not really worth the abstraction since you are not really swapping out template engines constantly.  Choose one, stick with it. But it still seems a lot of people want this. If you decide to change, swapping a module like `koa-swig` to `koa-hbs` is also not difficult.


Also, if your using libraries like React you are doing SSR anyway and template engines are also redundant:

```js
const render = (req, res) => {
  const vdom = render(
    <Shell title='Demo App' assets={assets}>
      <StaticRouter location={req.url} context={ctx}>
        <App />
      </StaticRouter>
    </Shell>
  )

  res.send('<!DOCTYPE html>' + vdom)
}
```

**Comment by DJviolin** [comment]
@queckezz Yes, `array.map` will work, the first loop implementation that I found [here](https://gist.github.com/wiledal/3c5b63887cc8a010a330b89aacff2f2e) used this:

```js
${Array(5).join(0).split(0).map((item, i) => `
  <div>I am item number ${i}.</div>
`).join('')}
```

However I decided to move the loop in a function, because this way I can keep clean my page template function, which is doing the rendering. My whole idea is if I need to write a complex function for some part, I will place that function in the same file's head or referencing with `require` from another file (slicing up my project to little parts). This way maybe that loop is portable, because I can use multiple times. In practice, this probably will not be the case, but than I write a `loops.js` and I call `loop.simple('<div>', state.array, '</div>')`. This is just an aesthetic choice.

**Comment by DJviolin** [comment]
@queckezz I just barely touched React, but maybe universal rendering also possible with template literals? It would be way awesome to make a stack where your Node projects doesn't need to include at least 3-4-5 packages (koa-views, nunjucks, react) and have universal rendering (in the browsers which supporting template literals, or transform them with babel).

**Comment by int64ago** [comment]
#85 && edd8e6f27cafb317418c0fd8619b69e6390bfe28
